const products = [
  {
    name: "Julgran",
    price: 500,
    quantity: 50,
    description: "En grön julgran för ditt hem.",
    img_path: ``,
  },
  {
    name: "Julljus",
    price: 100,
    quantity: 1300,
    description: "Ljusslinga för både inomhus- och utomhusbruk.",
    img_path: "https://example.com/images/julljus.jpg",
  },
  {
    name: "Adventsstjärna",
    price: 250,
    quantity: 100,
    description: "En vacker adventsstjärna som lyser upp ditt fönster.",
    img_path: "https://example.com/images/adventsstjarna.jpg",
  },
  {
    name: "Julkrans",
    price: 150,
    quantity: 75,
    description: "Dekorativ julkrans att hänga på dörren.",
    img_path: "https://example.com/images/julkrans.jpg",
  },
  {
    name: "Nyårsfyrverkerier",
    price: 400,
    quantity: 20,
    description: "Fyrverkerier för att fira in det nya året.",
    img_path: "https://example.com/images/nyarsfyrverkerier.jpg",
  },
  {
    name: "Pepparkakor",
    price: 60,
    quantity: 500,
    description: "Hembakade pepparkakor i alla former.",
    img_path: "https://example.com/images/pepparkakor.jpg",
  },
  {
    name: "Glögg",
    price: 120,
    quantity: 250,
    description: "Värmande glögg för vinterkvällarna.",
    img_path: "https://example.com/images/glogg.jpg",
  },
  {
    name: "Julslinga",
    price: 200,
    quantity: 80,
    description: "Ljusslinga som passar perfekt i julgranen.",
    img_path: "https://example.com/images/julslinga.jpg",
  },
  {
    name: "Julklappspapper",
    price: 30,
    quantity: 100,
    description: "Julklappspapper i festliga mönster.",
    img_path: "https://example.com/images/julklappspapper.jpg",
  },
  {
    name: "Nyårsdekorationer",
    price: 80,
    quantity: 120,
    description: "Nyårsdagsdekorationer för en festlig stämning.",
    img_path: "https://example.com/images/nyarsdekorationer.jpg",
  },
  {
    name: "Julgranspynt",
    price: 50,
    quantity: 200,
    description: "Fina julgranskulor och glitter.",
    img_path: "https://example.com/images/julgranspynt.jpg",
  },
  {
    name: "Julgodis",
    price: 150,
    quantity: 300,
    description: "Julens bästa godis för alla smaker.",
    img_path: "https://example.com/images/julgodis.jpg",
  },
  {
    name: "Nyårshattar",
    price: 25,
    quantity: 150,
    description: "Färgglada hattar för nyårsfesten.",
    img_path: "https://example.com/images/nyarshattar.jpg",
  },
  {
    name: "Julbordskrydda",
    price: 80,
    quantity: 90,
    description: "Kryddblandning som gör julbordet ännu godare.",
    img_path: "https://example.com/images/julbordskrydda.jpg",
  },
  {
    name: "Nyårslöfte-tavla",
    price: 110,
    quantity: 60,
    description: "En tavla att skriva dina nyårslöften på.",
    img_path: "https://example.com/images/nyarslofte-tavla.jpg",
  },
  {
    name: "Snögubbe",
    price: 100,
    quantity: 50,
    description: "En dekoration för att sprida julstämning.",
    img_path: "https://example.com/images/snogubbe.jpg",
  },
  {
    name: "Julskinka",
    price: 250,
    quantity: 120,
    description: "Traditionell julskinka för julbordet.",
    img_path: "https://example.com/images/julskinka.jpg",
  },
  {
    name: "Adventskalender",
    price: 180,
    quantity: 200,
    description: "En adventskalender för hela familjen.",
    img_path: "https://example.com/images/adventskalender.jpg",
  },
  {
    name: "Juleljus",
    price: 40,
    quantity: 1000,
    description: "Doftljus med julens bästa aromer.",
    img_path: "https://example.com/images/juleljus.jpg",
  },
  {
    name: "Julgransspel",
    price: 150,
    quantity: 30,
    description: "Julspel för hela familjen.",
    img_path: "https://example.com/images/julgransspel.jpg",
  },
  {
    name: "Julklappar",
    price: 500,
    quantity: 10,
    description: "Kreativa och roliga julklappar.",
    img_path: "https://example.com/images/julklappar.jpg",
  },
  {
    name: "Nyårsfestdräkt",
    price: 300,
    quantity: 50,
    description: "Elegant festdräkt för nyårsafton.",
    img_path: "https://example.com/images/nyarsfestdrakt.jpg",
  },
  {
    name: "Frostade fönsterklistermärken",
    price: 30,
    quantity: 200,
    description: "Frostade klistermärken för julfönstren.",
    img_path: "https://example.com/images/frostade_fonsterklistermarken.jpg",
  },
  {
    name: "Nyårsmössa",
    price: 50,
    quantity: 100,
    description: "Glittrig nyårsmössa för festligt firande.",
    img_path: "https://example.com/images/nyarsmossa.jpg",
  },
  {
    name: "Julpyntset",
    price: 120,
    quantity: 60,
    description: "Komplett julpyntset för hela hemmet.",
    img_path: "https://example.com/images/julpyntset.jpg",
  },
  {
    name: "Juleljus i glas",
    price: 80,
    quantity: 200,
    description: "Ljus i vackra glasburkar, perfekt för jul.",
    img_path: "https://example.com/images/juleljus_glas.jpg",
  },
  {
    name: "Julgransmatta",
    price: 220,
    quantity: 80,
    description: "Matta för att skydda golvet under julgranen.",
    img_path: "https://example.com/images/julgransmatta.jpg",
  },
  {
    name: "Julgransfot",
    price: 180,
    quantity: 90,
    description: "Stabil fot för att hålla julgranen på plats.",
    img_path: "https://example.com/images/julgransfot.jpg",
  },
  {
    name: "Grankvistar",
    price: 75,
    quantity: 150,
    description: "Färska grankvistar till dekoration.",
    img_path: "https://example.com/images/grankvistar.jpg",
  },
  {
    name: "Julmus",
    price: 30,
    quantity: 500,
    description: "Julens bästa julmust.",
    img_path: "https://example.com/images/julmus.jpg",
  },
  {
    name: "Julstjärna",
    price: 200,
    quantity: 110,
    description: "Lysande julstjärna för fönstret.",
    img_path: "https://example.com/images/julstjarna.jpg",
  },
  {
    name: "Adventsljusstake",
    price: 120,
    quantity: 70,
    description: "Klassisk adventsljusstake med fyra ljus.",
    img_path: "https://example.com/images/adventsljusstake.jpg",
  },
  {
    name: "Julgransbelysning",
    price: 200,
    quantity: 200,
    description: "Julgransbelysning som skapar den rätta stämningen.",
    img_path: "https://example.com/images/julgransbelysning.jpg",
  },
  {
    name: "Julbakset",
    price: 90,
    quantity: 150,
    description: "Set för att baka pepparkakor och lussekatter.",
    img_path: "https://example.com/images/jul.jpg",
  },
];

const productData = products.map((product) => ({
  ...product,
  img_path: `https://placehold.co/200?text=${encodeURIComponent(
    product.name
  )}&font=roboto`,
}));

export { productData };
